name: fmcv_transcript
services:
  records_server_gpu:
    container_name: ps3_records_server_gpu
    image: fortunemachinecomputer/fmcv_transcripts:latest
    restart: always
    profiles: [gpu]
    volumes:
      - ./data:/app/data
      - .cache:/root/.cache
      - ./passcode.txt:/app/passcode.txt
      - ./ssl_certs:/app/ssl_certs
    env_file:
      - .env
    ports:
      - "${HOST_RTMP_PORT}:1935"
    hostname: ps3_records_server
    command: "python3 recording_server_start.py"
    networks:
      - fmcv_internal
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ['gpu']

  records_backend_gpu:
    container_name: ps3_records_backend_gpu
    image: fortunemachinecomputer/fmcv_transcripts:latest
    restart: always
    profiles: [gpu]
    volumes:
      - ./data:/app/data
      - .cache:/root/.cache
      - ./passcode.txt:/app/passcode.txt
      - ./ssl_certs:/app/ssl_certs
    env_file:
      - .env
    ports:
      - "${HOST_RECORDS_PORT}:8999"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    hostname: ps3_records_backend
    command: "python3 recording_backend_start.py"
    networks:
      - fmcv_internal
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ['gpu']

  records_streaming_gpu:
    container_name: records_streaming_gpu
    image: fortunemachinecomputer/fmcv_transcripts:latest
    restart: always
    profiles: [gpu]
    build:
      context: .
      target: gpu
    volumes:
      - ./data:/app/data
      - .cache:/root/.cache
      - ./passcode.txt:/app/passcode.txt
      - ./ssl_certs:/app/ssl_certs
    env_file:
      - .env
    ports:
      - "${HOST_M3U8_PORT}:8686"
    hostname: live_streaming_gpu
    command: "python3 m3u8_start.py"
    networks:
      - fmcv_internal
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ['gpu']

  records_server_cpu:
    container_name: ps3_records_server_cpu
    image: fortunemachinecomputer/fmcv_transcripts_cpu:latest
    restart: always
    profiles: [cpu]
    volumes:
      - ./data:/app/data
      - .cache:/root/.cache
      - ./passcode.txt:/app/passcode.txt
      - ./ssl_certs:/app/ssl_certs
    env_file:
      - .env
    ports:
      - "${HOST_RTMP_PORT}:1935"
    hostname: ps3_records_server
    command: "python3 recording_server_start.py"
    networks:
      - fmcv_internal

  records_backend_cpu:
    container_name: ps3_records_backend_cpu
    image: fortunemachinecomputer/fmcv_transcripts_cpu:latest
    restart: always
    profiles: [cpu]
    volumes:
      - ./data:/app/data
      - .cache:/root/.cache
      - ./passcode.txt:/app/passcode.txt
      - ./ssl_certs:/app/ssl_certs
    env_file:
      - .env
    ports:
      - "${HOST_RECORDS_PORT}:8999"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    hostname: ps3_records_backend
    command: "python3 recording_backend_start.py"
    networks:
      - fmcv_internal

  records_streaming_cpu:
    container_name: records_streaming_cpu
    image: fortunemachinecomputer/fmcv_transcripts_cpu:latest
    restart: always
    profiles: [cpu]
    build:
      context: .
      target: cpu
    volumes:
      - ./data:/app/data
      - .cache:/root/.cache
      - ./passcode.txt:/app/passcode.txt
      - ./ssl_certs:/app/ssl_certs
    env_file:
      - .env
    ports:
      - "${HOST_M3U8_PORT}:8686"
    hostname: records_streaming_cpu
    command: "python3 m3u8_start.py"
    networks:
      - fmcv_internal

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=docker-cluster
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    # Not exposing ports 9200 and 9300 as requested
    networks:
      - fmcv_internal

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.2
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "${HOST_KIBANA_PORT}:5601"
    depends_on:
      - elasticsearch
    networks:
      - fmcv_internal

volumes:
  elasticsearch-data:
    driver: local

networks:
  fmcv_internal:
    driver: bridge